### ISSUE TITLE
Octavia support

### ISSUE THREAD

**Issue by remche** [remche/terraform-openstack-rke#26]
It would be great to support Octavia. We should then provision a LB for master HA and take advantage of Octavia Kubernetes cloud provider support.

**Comment by davidspek** [comment]
Don't quite have this template working yet, but I would like to suggest using Octavia with OVN. I am trying this setup so I do not need to dedicate a node (or create an LXD container) for the neutron gateway. https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html

**Comment by Linutux** [comment]
I think OVN is not (yet) the way to go. The article lists some disadvantages:


OVN has its own set of limitations when considered as an Load Balancer driver. These include:

    OVN currently supports TCP and UDP, so Layer-7 based load balancing is not possible with OVN.

    While Health Checks are now available in OVN, they are not currently implemented in OVN’s Provider Driver for Octavia.

    There are currently no Health Monitors in OVN’s Provider Driver for Octavia. Therefore Health Checking is not possible with OVN.
