### ISSUE TITLE
use_ssh_agent

### ISSUE THREAD

**Issue by tcassaert** [remche/terraform-openstack-rke#63]
I was trying to make this Terraform module to work on, but I got a little confused about the `use_ssh_agent`. What exactly does it do?

The default is set to true, but that means you can't provide a private SSH key to access your newly provisioned nodes:
https://github.com/remche/terraform-openstack-rke/blob/5b4dfd8075171e4d589267f17cb5337b48e7165e/modules/rke/main.tf#L9

I was only getting timeouts with the default value:

```
Error: timeout - last error: Error connecting to bastion: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

When setting the `use_ssh_agent` on false, I could get connection.

**Comment by remche** [comment]
Thanks for the bug report.

`use_ssh_agent` allow to use [ssh agent](https://linux.die.net/man/1/ssh-agent) with encrypted ssh keys.
If you dont use it, you need to disable it or rke will fail. I will add a doc entry on that point !

**Comment by remche** [comment]
Done in b71c52f, @tcassaert is that clearer ?

**Comment by tcassaert** [comment]
Looks good! Thanks for the quick response!
